#!/bin/bash 
############################

PROG=`basename $0`
if [ $# -ne 3 ]
then
    echo "Usage: $PROG pythiaconfig.cmnd cardname comment"
    exit;
fi

function setenv(){ export $1=$2; }

setenv pyconfigname $1
setenv cardname $2
setenv comment $3
#################################
# Output file locations
#################################
setenv Main_DIR     `pwd`
setenv DoWhat       pythiaChargedDijet
setenv oname        pythia8226_pp5TeV_$pyconfigname_chargedjets_$comment
setenv Disk         `pwd`
setenv OUT_ERRORS   $Disk/outputs/${oname}/errors
setenv Out_DIR      $Disk/outputs/${oname}/data
setenv LOG_DIR      $Disk/outputs/${oname}/logs
#################################
# Need for serial job in sepeli(pbs)
#################################
setenv noFileToRun 1000
#################################

mkdir -p $OUT_ERRORS
mkdir -p $Out_DIR
mkdir -p $LOG_DIR

#################################
# Runlist to scan
#################################

# simplify this !!!
cat << EOF > exec_jetjt_$comment
#!/bin/bash -f
cd $Main_DIR
source setup.sh.elc
export what=$DoWhat
export sedN=6000
export iseg=\$SLURM_ARRAY_TASK_ID
sedN=\`expr \$sedN + \${iseg}\`
export outfile=$Out_DIR/$DoWhat-\$sedN.root
export Log=$LOG_DIR/$DoWhat-\$sedN.log
./\${what} $pyconfigname $cardname \$outfile \$sedN  >& \$Log
cd $Main_DIR
EOF
#\${what} \$outfile \$sedN 5000000 >& \$Log
chmod +x exec_jetjt_$comment
    sbatch -v --array=1-$noFileToRun exec_jetjt_$comment -J $comment  -e $OUT_ERRORS -o $OUT_ERRORS
